# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/99_test_costs.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/99_test_costs.ipynb 4
import unittest
from .._costs import pairwise_costs, average_costs, total_costs
from numpy.testing import assert_array_equal
