# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ddop2',
                'doc_host': 'https://opimwue.github.io',
                'git_url': 'https://github.com/opimwue/ddop2',
                'lib_path': 'ddop2'},
  'syms': {'ddop2.core': {'ddop2.core.foo': ('core.html#foo', 'ddop2/core.py')}}}
